version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  redis:
    image: redis
    command: redis-server --requirepass Dpk123456
    ports:
      - "6378:6379"
    networks:
      - elk

  elastalert:
    image: bitsensor/elastalert:3.0.0-beta.1 # 适配ELK 7.11.2 版本
    networks:
      - elk
    volumes:
      - type: bind
        source: ./elastalert/config/elastalert.yaml
        target: /opt/elastalert/config.yaml
        read_only: true 
      - type: bind
        source: ./elastalert/config/elastalert-test.yaml
        target: /opt/elastalert/config-test.yaml
        read_only: true 
      - type: bind
        source: ./elastalert/config/config.json
        target: /opt/elastalert-server/config/config.json
        read_only: true 
      - type: bind
        source: ./elastalert/rules
        target: /opt/elastalert/rules
      - type: bind
        source: ./elastalert/rule_templates
        target: /opt/elastalert/rules_templates
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
